### PR TITLE
Storm recipe related changes

### PR DESCRIPTION
**Pull request by dfilppi**
Many changes here, mainly around making a viable word count demo.  Also, xap9x recipe updates.

### CODE REVIEW

**Comment by dfilppi** [comment]
Whats the hold up?

**Comment by tamirko** [comment]
Dewayne, 
Please rebase, revise and then push again.
Some packages have been changed and it's impossible to merge tens of files manually.
10x.

**Comment by dfilppi** [comment]
I think it's good to go now.

**Comment by dfilppi** [comment]
for some reason commit b13cdb3 didn't make it.  it's important

**Pull request merged**
