### PR TITLE
updated storm-nimbus recipe

### PR DESCRIPTION
**Pull request by dfilppi**
Added monitoring plugin, custom commands, support for xapstream topology deployment

### CODE REVIEW

**Comment by uric** [comment]
Thanks Dewayne.  A few questions: 
- Are you planning to make the XAP recipe support HA? 
- Do you deploy the PU manually to XAP? if so are you planning to change this?
- Why are you using Java plugins and not Groovy probes (easier to maintain)?

**Comment by dfilppi** [comment]
1. Ha isn't possible with storm.  Xap recipe could easily be changed though, assume lite version will cooperate.
2. No, automatically.
3. Probably could convert.  Was easier to develop in java.  I like to see problems prior to runtime.

DeWayne

Sent from my iPad

On Feb 25, 2013, at 5:26 AM, "Uri Cohen" <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks Dewayne. A few questions:
-   Are you planning to make the XAP recipe support HA?
-   Do you deploy the PU manually to XAP? if so are you planning to change this?
-   Why are you using Java plugins and not Groovy probes (easier to maintain)?

**Comment by uric** [comment]
1. Yes, I meant XAP which is currently single instance. The only trick here is to expose the LOCATORS variable across the environment.  
2. Very cool. Didn't see where the magic happens (deploying a data grid). Can you point me to it?  
3. You can still do it, even more convenient in groovy using groovy of groovysh and running in script mode (there's no need to compile and build which makes things simpler)

In any case I'll merge this for now so it's out there. Just fix the readme to read "experimental" or "under construction"

**Comment by dfilppi** [comment]
It's in the postStart method on the xapstream recipe.

**Pull request merged**
